variavel=input('Digite algo: ')
print('O tipo desse valor é ' , type(variavel))
print('Só tem espaços?' , variavel.isspace())
print('É um número?' , variavel.isnumeric())
print('É alfabético?' , variavel.isalpha())
print('É alfanumérico?' , variavel.isalnum())
print('É maiúsculo?' , variavel.isupper())
print('É minúsculo?' , variavel.islower())
print('Está capitalizada?' , variavel.istitle())